name: Robot Bunny Reboot
favicon: null
layout_spectrum: 0.13140648254193366
typography_spectrum: 0.07848780718632042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.9575786250643432
  lightness: 0.9240868277847767
  saturation: 0.2863876132760197
  rhythmicContrast: 0.6307061207480729
purpose: []
